try{
    console.log(a)
    let a = 3;
}catch(error){
    console.loog('‘let перед использованием нужно объявить’')
}

 

   
    
 



